### ISSUE TITLE
Research paging on the series results pages.

### ISSUE THREAD

**Issue by jonpage** [UHERO/udaman#11]
See if paging would be acceptable on the series display pages (i.e., do we really have to show all the data points?). Showing all the data points is expensive.

**Comment by cbonham** [comment]
Not sure what "paging" means.

**Comment by jonpage** [comment]
Paging refers to splitting long series across multiple pages. For a daily series that goes back 10 years, we could display just the most recent 30 observations, while still allowing the user to navigate through or download the entire series.

**Comment by jonpage** [comment]
Will be resolved by #24
